DefaultContentLanguage = "en"
author = "He Yeshuang"
baseURL = ""
copyright = "Copyright © 2008–2019"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
googleAnalytics = "UA-FAKE" # or "G-xxxxxxxx" in Google Analytics v4, in Hugo v0.82+
hasCJKLanguage = true
languageCode = "cn"
theme = "hugo-theme-tokiwa"
title = "My messy collection"

[markup]
  [markup.highlight]
  style = "monokailight"

  [markup.goldmark.renderer]
  unsafe = true

[params]
  bannerFont = "fonts/exampleFont"
  description = """
  Try using the search bar, the site is indeed cluttered!
  """
  env = "production" # for Google Analytics and DISQUS.
  favicon = "img/favicon-32x32.png"
  fuse = true # for searchbox. "JSON" must be added to output contents. See [outputs].
  math = true # for introducing $KaTeX$
  useChineseFonts = true
  postDateFormat = "2006-1-2"

  # Social links section (use params instead of deprecated .Site.Social)
  [params.social]
  github = "https://github.com/AlexD2003"
  instagram = "https://www.instagram.com/alex_domnit/"
  mail = "mailto:alexandru.domnit@stud.ubbcluj.ro"
  # twitter = "https://twitter.com/"
  # weibo = "http://example.com/"
  # youtube = "https://youtube.com/"
  # zhihu = "http://example.com/"

[menu]
  # Shown in the side menu.
  [[menu.main]]
  identifier = "post"
  name = "Posts"
  url = "/post/"
  weight = 1

  [[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 2

  [[menu.main]]
  name = "Categories"
  url = "/categories/"
  weight = 2

  [[menu.main]]
  identifier = "about"
  name = "About me"
  url = "/about/aboutme/"
  weight = 312

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[outputs]
  home = ["HTML", "RSS", "JSON"]
